config/routes.rb
Dashboard::Application.routes.draw do
  get "users" => 'users#index'

  get 'desktop/' => 'home#desktop'

  get 'messages/search' => 'messages#search'
  devise_for :users
  resources :keys, :only => [:index,:new, :create, :destroy]
  resources :messages do
    member do
      put 'unread'
      put 'read'
      put 'archive'
      put 'unarchive'
    end
  end
  resources :master_projects do
    get 'finish', :on => :member
  end
  resources :projects do

    get 'tree', :on => :member
    get "tree/:commit_id" => "projects#tree", :on => :member
    get "tree/:commit_id/:path" => "projects#tree",
      :on => :member,
      :as => :tree_file,
      :constraints => {
      :id => /[a-zA-Z0-9_\-]+/,
      :commit_id => /[a-zA-Z0-9]+/,
      :path => /.*/
    }

    get 'users', :on => :member
    get 'set_active', :on => :member
    get 'finish', :on => :member
    resources :memberships
    resources :documents
    resources :tasks do
      member do
        put 'complete'
        put 'start'
      end
    end
  end

  resources :versions
  get 'roles/:id' => 'roles#edit', :as => :edit_role
  put 'roles/:id' => 'roles#update', :as => :edit_role

  authenticate :user do
    root :to => 'home#desktop'
  end
  root :to => 'home#home'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, :class_name => 'User'
  belongs_to :master_project
  has_many :deliveries, :autosave => true
  has_many :receivers, :through => :deliveries, :source => :user

  after_save :send_message


  def archive
    deliveries.map(&:archive)
  end

  private

  def send_message
    receivers.each do |r|
      Delivery.new :user_id => r, :message => self, :read => false
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ActionController::Base

  layout 'application'
  def index
    @deliveries = current_user.deliveries.unread.paginate(:page => params[:deliveries_page], :per_page => Delivery::PER_PAGE)
    @sent_messages = current_user.sent_messages.paginate(:page => params[:sent_page], :per_page => Delivery::PER_PAGE)
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new params[:message]
    @message.master_project = current_user.current_master_project
    @message.sender = current_user
    @message.save
    flash[:notice] = 'Mensagem enviada com sucesso!'
    redirect_to messages_path
  end

  def show
    @delivery = current_user.deliveries.find_by_message_id(params[:id])
    @delivery.read!
    @delivery.save
    render :show
  end

  def destroy
  end

  def unread
    @delivery = current_user.deliveries.find_by_message_id(params[:id])
    @delivery.unread!
    @delivery.save
    flash[:notice] = 'Mensagem marcada como Nao lida'
    redirect_to messages_path
  end

  def read
    @delivery = current_user.deliveries.find_by_message_id(params[:id])
    @delivery.read!
    @delivery.save
    flash[:notice] = 'Mensagem marcada como lida'
    redirect_to messages_path
  end

  def archive
    @delivery = current_user.deliveries.find_by_message_id(params[:id])
    @delivery.archive
    @delivery.save
    flash[:notice] = 'Mensagem arquivada com sucesso.'
    redirect_to messages_path
  end

  def unarchive
    @delivery = current_user.deliveries.find_by_message_id(params[:id])
    @delivery.unarchive
    @delivery.save
    flash[:notice] = 'Mensagem desarquivada com sucesso.'
    redirect_to messages_path
  end

  def search
    begin
      @deliveries = current_user.deliveries.search(params).paginate(:page => params[:deliveries_page], :per_page => params[:per_page] || Delivery::PER_PAGE)
    rescue
      @deliveries = current_user.deliveries.unread.paginate(:page => params[:deliveries_page], :per_page => params[:per_page] || Delivery::PER_PAGE)
    end
  end

end

app/views/messages/_deliveries.html.haml
.row
  .span10
    %h2
      Mensagens recebidas
  = render 'search_form'
%table.condensed-table.zebra-striped
  %thead
    %tr
      %th Assunto
      %th Remetente
      %th Data
      %th Ações
  %tbody
    - @deliveries.each do |d|
      %tr
        %td
          - if d.unread?
            =link_to "<span class='label success'>NOVA</span>".html_safe, message_path(d.message)
          =link_to d.message.subject, message_path(d.message)
        %td= d.user
        %td= I18n.l(d.created_at, :format => :short)
        %th
          =link_to image_tag('icons/email_open.png'), read_message_path(d.message), :method => :put if d.unread?
          =link_to image_tag('icons/email.png'), unread_message_path(d.message), :method => :put unless d.unread?
          =link_to image_tag('icons/folder.png'), archive_message_path(d.message), :method => :put unless d.archived?
          =link_to image_tag('icons/folder_go.png'), unarchive_message_path(d.message), :method => :put if d.archived?


= will_paginate @deliveries, :param_name => :deliveries_page

app/views/messages/_header.html.haml
.row
  .span12
    %h1
      Mensagens de #{current_user}
  .span4
    = link_to image_tag('icons/email_add.png') + ' Nova mensagem', new_message_path, :class => 'btn large success'

app/views/messages/_search_form.html.haml
=form_tag '/messages/search', :method => :get do
  %fieldset
    .row
      .span8
        =label_tag 'Data'
        .input.clearfix
          .inline-inputs
            = text_field_tag :from, params[:from], :class => 'datepicker small', :size => 10
            %span{:style => 'font-size: 10pt'} Até
            = text_field_tag :to, params[:to], :class => 'datepicker small', :size => 10
            %span.help-block Datas no horário de Brasilia.
        .input.clearfix
          %ul.inputs-list
            %li
              %label
                = check_box_tag :read, 1, params[:read]
                %span Incluir lidas
              %label
                = check_box_tag :archived, 1, params[:archived]
                %span Incluir arquivadas
      .span8
        = label_tag 'Remetente'
        .input.clearfix
          = select_tag :sender, options_from_collection_for_select(User.where(:id => current_user.deliveries.map(&:message).map(&:sender_id).uniq), :id, :to_s, params[:sender]), :include_blank => true
        = label_tag 'Projeto Guarda chuva: '
        .input.clearfix
          = select_tag :master_project, options_from_collection_for_select(current_user.projects.map(&:master_project).uniq, :id, :name, current_user.current_master_project.id), :include_blank => true
        = label_tag  'Por Pagina: '
        .input.clearfix
          = select_tag :per_page, options_for_select([5,10,20,50], 10)
    .row
      .span3.offset6
        = submit_tag 'Filtrar', :class => 'btn primary'
        = link_to 'Limpar', messages_path, :class => 'btn'

app/views/messages/index.html.haml
.whitebox.span16
  = render 'header'
  = render 'deliveries'
  .row
    .span10
      %h2
        Mensagens enviadas

  %table.condensed-table.zebra-striped
    %thead
      %tr
        %th Assunto
        %th Data
    %tbody
      - @sent_messages.each do |msg|
        %tr
          %td=link_to msg.subject, message_path(msg)
          %td= I18n.l(msg.created_at, :format => :short)
  = will_paginate @sent_messages, :param_name => :sent_page

app/views/messages/new.html.haml
.whitebox.span16
  .row
    .span16
      = form_for(@message) do |f|
        %fieldset
          %legend
            %h2 Nova Mensagem
          =label_tag 'Destinatários'
          .input
            =f.select :receiver_ids, options_from_collection_for_select(User.all, :id, :to_s, params[:sender]),{}, :multiple => true
          =label_tag 'Assunto'
          .input
            =f.text_field :subject, :class => 'span13'
          =label_tag 'Mensagem'
          .input
            =f.text_area :body, :class => 'span13'

        .row
          .span4.offset11
            = f.submit 'Enviar', :class => 'btn success'
            = link_to 'Limpar', new_message_path, :class => 'btn danger'
            = link_to 'Voltar', messages_path, :class => 'btn'

app/views/messages/search.html.haml
.whitebox.span16
  = render 'header'
  = render 'deliveries'

app/views/messages/show.html.haml
.whitebox.span16
  %h1
    = @delivery.message.subject
  .row
    .span8
      %h4
        De: #{@delivery.message.sender}
        %small
          = I18n.l(@delivery.message.created_at, :format => :short)
    .span5.offset3
      = link_to 'Marcar como não lida', unread_message_path(@delivery.message), :method => :put, :class => 'btn primary' if @delivery.message.sender != current_user
      = link_to 'Arquivar', archive_message_path(@delivery.message), :method => :put, :class => 'btn info' unless @delivery.archived?
      = link_to 'Desarquivar', unarchive_message_path(@delivery.essage), :method => :put, :class => 'btn info' if @delivery.archived?
  .row
    .span16
      = @delivery.message.body