config/routes.rb
Dashboard::Application.routes.draw do
  get "users" => 'users#index'

  get 'desktop/' => 'home#desktop'

  get 'messages/search' => 'messages#search'
  devise_for :users
  resources :keys, :only => [:index,:new, :create, :destroy]
  resources :messages do
    member do
      put 'unread'
      put 'read'
      put 'archive'
      put 'unarchive'
    end
  end
  resources :master_projects do
    get 'finish', :on => :member
  end
  resources :projects do

    get 'tree', :on => :member
    get "tree/:commit_id" => "projects#tree", :on => :member
    get "tree/:commit_id/:path" => "projects#tree",
      :on => :member,
      :as => :tree_file,
      :constraints => {
      :id => /[a-zA-Z0-9_\-]+/,
      :commit_id => /[a-zA-Z0-9]+/,
      :path => /.*/
    }

    get 'users', :on => :member
    get 'set_active', :on => :member
    get 'finish', :on => :member
    resources :memberships
    resources :documents
    resources :tasks do
      member do
        put 'complete'
        put 'start'
      end
    end
  end

  resources :versions
  get 'roles/:id' => 'roles#edit', :as => :edit_role
  put 'roles/:id' => 'roles#update', :as => :edit_role

  authenticate :user do
    root :to => 'home#desktop'
  end
  root :to => 'home#home'

end

app/views/shared/_up_bar.html.haml
.topbar
  .topbar-inner
    .container
      %h3
        =link_to 'DashBoard', desktop_path
      %ul.nav
        - if Member === current_user
          %li
            =link_to 'Tarefas', project_tasks_path(current_user.current_project)
          %li
            =link_to 'Repositório', tree_project_path(current_user.current_project)
        - elsif Manager === current_user
          %li
            =link_to 'Projetos Guarda-chuva', master_projects_path
        %li
          =link_to 'Mensagens', messages_path
        %li
          =link_to 'Chaves', keys_path
      %ul.nav.secondary-nav
        %li.dropdown
          %a.dropdown-toggle{:href => '#'}=current_user.current_project.name
          %ul.dropdown-menu
            -current_user.project_list.each do |project|
              %li
                =link_to project.name, set_active_project_path(project)
        %li
          =link_to current_user, edit_user_registration_path
        %li
          =link_to 'Sair', destroy_user_session_path



- if flash[:notice]
  .alert-message.success
    %a{:class=>'close', :href=>'#'}×
    %p= flash[:notice]
- if flash[:alert]
  .alert-message.error
    %a{:class=>"close", :href=>"#"}×
    %p= flash[:alert]