config/routes.rb
Dashboard::Application.routes.draw do
  get "users" => 'users#index'

  get 'desktop/' => 'home#desktop'

  get 'messages/search' => 'messages#search'
  devise_for :users
  resources :keys, :only => [:index,:new, :create, :destroy]
  resources :messages do
    member do
      put 'unread'
      put 'read'
      put 'archive'
      put 'unarchive'
    end
  end
  resources :master_projects do
    get 'finish', :on => :member
  end
  resources :projects do

    get 'tree', :on => :member
    get "tree/:commit_id" => "projects#tree", :on => :member
    get "tree/:commit_id/:path" => "projects#tree",
      :on => :member,
      :as => :tree_file,
      :constraints => {
      :id => /[a-zA-Z0-9_\-]+/,
      :commit_id => /[a-zA-Z0-9]+/,
      :path => /.*/
    }

    get 'users', :on => :member
    get 'set_active', :on => :member
    get 'finish', :on => :member
    resources :memberships
    resources :documents
    resources :tasks do
      member do
        put 'complete'
        put 'start'
      end
    end
  end

  resources :versions
  get 'roles/:id' => 'roles#edit', :as => :edit_role
  put 'roles/:id' => 'roles#update', :as => :edit_role

  authenticate :user do
    root :to => 'home#desktop'
  end
  root :to => 'home#home'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def desktop
    if current_user.is_a? Manager
      @project = current_user.current_master_project
      redirect_to @project
    else
      @project = current_user.current_project
      redirect_to @project
    end
  end

  def home

  end

  private

  def manager_desktop

  end
end

app/views/home/_project_info.html.haml
%p.header
  = project.name
%h2
  Informações:
  %p.links
    = link_to image_tag('icons/application_edit.png'), edit_project_path(project), :title => 'Editar projeto' if can? :edit, project
    = add_project_to_calendar project
%h3
  Descriçao:
%p.desc
  = project.description
%h3
  Data Final:
%p.desc
  = project.end_date

app/views/home/desktop.html.haml
.project-box
  %p.header
    = @project.name
  %h2
    Informações:
    %p.links
      = link_to image_tag('icons/application_edit.png'), edit_project_path(@project), :title => 'Editar projeto' if can? :edit, @project
      = link_to image_tag('icons/application_go.png'), finish_project_path(@project), :title => 'Entregar projeto'
  %h3
    Descriçao:
  %p.desc
    = @project.description
  %h3
    Data Final:
  %p.desc
    = @project.end_date
  %h3
    Repositorio:
  %p.desc
    = @project.repo_url
    = link_to image_tag('icons/page_white_go.png'), tree_project_path(@project.id)

  %h2
    Colaboradores:
    %p.links
      = link_to image_tag('icons/user_add.png'), new_project_membership_path(@project)
  %ul.users
    - @project.memberships.each do |membership|
      %li.user
        %p.desc
          = membership.user
        %p.links
          = link_to image_tag('icons/user_edit.png'), edit_project_membership_path(membership.project,membership) if can? :edit, membership
          = link_to image_tag('icons/user_delete.png'), { :controller => :memberships, :action => :destroy, :id => membership, :project_id => @project }, :method => :delete, :confirm => 'Tem certeza?' if can? :destroy, membership
  %h2
    Tarefas:
    %p.links
      = link_to image_tag('icons/clock_add.png'), new_project_task_path(@project)
  %ul.tasks
    - @project.tasks.each do |task|
      %li.task
        %p.desc
          = link_to task, project_task_path(@project, task)
          %span.task-info
            = task.status
        %p.links
          = link_to image_tag('icons/clock_stop.png'), complete_project_task_path(task.project, task), :method => :put if task.started?
          = link_to image_tag('icons/clock_play.png'), start_project_task_path(task.project, task), :method => :put unless task.started? || task.completed?
  %h2
    Documentos:
    %p.links
      = link_to image_tag('icons/page_white_add.png'), new_project_document_path(@project)
  %ul.documents
    - @project.documents.each do |doc|
      %li
        %p.desc
          = image_tag "icons/page_white_get.png"
          = link_to doc.file_identifier, project_document_path(doc.project,doc)
          = doc.description
        %p.links
          = link_to image_tag('icons/page_white_edit.png'), edit_project_document_path(@project,doc) if can? :edit, doc
          = link_to image_tag('icons/page_white_delete.png'), {:controller => :documents, :action => :destroy, :id => doc.id, :project_id => doc.project}, :method => :delete, :confirm => 'Tem certeza?' if can? :destroy, doc

app/views/home/home.html.haml
.content
  .banner-top
    = image_tag 'banner-top.png'

  .desc
    Lorem ipsum dolor sit amet, nulla vivamus mauris vehicula quis consequat, enim eu magnis sapien morbi, 
    wisi suscipit etiam, enim vestibulum justo nulla, molestie ad ut quis orci sed ornare. Id sagittis, libero amet et id, feugiat sagittis at tempor vel, dui vel dignissim ullamcorper elit lorem, pede eleifend ornare quam.
    Sit ullamcorper id, quisque vel in tempor augue vel urna, unde dui sed et, diam eleifend nec faucibus ac ut viverra, turpis ut felis. Quisque varius ut urna. Libero porttitor nunc, nulla et urna ligula nunc justo ipsum, scelerisque massa felis nonummy arcu. Sapien dapibus, suscipit orci, elit placerat ante risus enim, volutpat ultricies vitae sagittis. Non lacus risus duis mauris, mollis scelerisque habitant, at ipsum, pede dignissim odio lobortis ut, egestas nunc libero non scelerisque libero scelerisque. Wisi erat dui faucibus, eu fringilla ac non praesent, dictum eros.
  
  .login
    = link_to t('sign_in'), new_user_session_path
    = link_to t('sign_up'), new_user_registration_path

app/views/home/manager_desktop.html.haml
.project-box
  = render :partial => 'project_info', :locals => { :project => @project }

  %h2
    Projetos:
    %p.links
      = link_to image_tag('icons/application_add.png'), new_project_path
      = link_to image_tag('icons/application_go.png'), finish_master_project_path(@project), :title => 'Encerrar projeto'
  %ul.sub-projects
    - @project.projects.each do |project|
      %li.project
        %p.desc
          = link_to project.name, project