config/routes.rb
Dashboard::Application.routes.draw do
  get "users" => 'users#index'

  get 'desktop/' => 'home#desktop'

  get 'messages/search' => 'messages#search'
  devise_for :users
  resources :keys, :only => [:index,:new, :create, :destroy]
  resources :messages do
    member do
      put 'unread'
      put 'read'
      put 'archive'
      put 'unarchive'
    end
  end
  resources :master_projects do
    get 'finish', :on => :member
  end
  resources :projects do

    get 'tree', :on => :member
    get "tree/:commit_id" => "projects#tree", :on => :member
    get "tree/:commit_id/:path" => "projects#tree",
      :on => :member,
      :as => :tree_file,
      :constraints => {
      :id => /[a-zA-Z0-9_\-]+/,
      :commit_id => /[a-zA-Z0-9]+/,
      :path => /.*/
    }

    get 'users', :on => :member
    get 'set_active', :on => :member
    get 'finish', :on => :member
    resources :memberships
    resources :documents
    resources :tasks do
      member do
        put 'complete'
        put 'start'
      end
    end
  end

  resources :versions
  get 'roles/:id' => 'roles#edit', :as => :edit_role
  put 'roles/:id' => 'roles#update', :as => :edit_role

  authenticate :user do
    root :to => 'home#desktop'
  end
  root :to => 'home#home'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_paper_trail

  validates :name, :presence => true, :uniqueness => true
  validates :description, :presence => true

  belongs_to :master_project

  has_many :memberships
  has_many :members,  :through    => :memberships,
                      :source     => :user,
                      :conditions => 'memberships.manager = 0'

  has_many :managers, :through    => :memberships,
                      :source     => :user,
                      :conditions => 'memberships.manager = 1'
  has_many :tasks
  has_many :documents

  delegate :end_date, :to => :master_project

  before_save :update_repo

  def update_repo
    Gitosis.new.configure do |r|
      r.update_project(repo_name, member_keys)
    end
  end

  def repo_url
   "#{GITOSIS['git_user']}@#{GITOSIS['host']}:/#{repo_name}.git"
  end

  def repo
    @repo ||= Grit::Repo.new(GITOSIS['base_path'] + repo_name + '.git')
  rescue Grit::NoSuchPathError
    raise 'Repositorio sem arquivos #TODO Fazer uma view aqui'
  end

  def repo_name
    name.parameterize
  end

  def colaborators
    members + managers
  end

  def finish
    self.finished = true
  end

  def finished?
    finished
  end
  def member_keys
    members.map(&:pub_keys).flatten
  end

  def calendar_string
    CGI.escape("#{name} #{master_project.end_date.to_s}")
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ActionController::Base
  load_and_authorize_resource :project
  before_filter :find_current

  layout 'application'

  def new
    @project = Project.new
  end

  def edit
  end

  def show
  end

  def index
    @projects = current_user.projects
  end

  def update

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end


  def create
    @project = Project.new(params[:project])
    @project.master_project = current_user.current_master_project
    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Projeto criado com sucesso!') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end

  end

  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(root_url) }
      format.xml  { head :ok }
    end
  end

  def users
    @members  = @project.members
    @managers = @project.managers
  end

  def set_active
    if current_user.is_a? Manager
      current_user.current_master_project_id = params[:id]
    else
      current_user.current_project_id = params[:id]
    end
    current_user.save
    redirect_to current_user.current_project
  end

  def finish
    @project.finish
    @project.save
    redirect_to(@project)
  end

  def tree
    @repo = @project.repo

    if params[:commit_id].present?
      @tree = @repo.commits(params[:commit_id]).first.tree
    else
      @tree = @repo.tree
    end

    @commit = @repo.head.name

    if params[:path]
      @tree = @tree / params[:path]
    end

    if Grit::Tree === @tree
      render 'tree'
    else
      render 'blob'
    end
  end

  private

  def find_current
    if Manager === current_user
      @project = Project.find_by_id(params[:id])
    else
      @project = current_user.current_project
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

end

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  %fieldset
    -if @project.new_record?
      .clearfix{:class => error_for(@project, :name)}
        = f.label :name, 'Nome'
        .input
          =f.text_field :name, :class => 'xxlarge'
          =error_message_for @project, :name
    .clearfix{:class => error_for(@project,:description)}
      = f.label :description, 'Descrição'
      .input
        =f.text_area :description, :class => "xxlarge"
        =error_message_for @project, :description

    .row
      .span3.offset12
        = f.button :submit, :class => 'btn success'

app/views/projects/blob.html.haml
.whitebox.span16
  %h2
    = "#{breadcrumb(@project,@commit,params[:path])}".html_safe
  .colorcode
    :preserve
      #{raw @tree.colorize}

app/views/projects/edit.html.haml
.whitebox.span16
  %h1
    Editar Projeto
  = render 'form'

app/views/projects/index.html.haml
.projects
  - if @projects.present?
    %p.header Projetos - Membro
    - @projects.each_with_index do |project,index|
      .project{:class => [index == 0 && "first", cycle("even", "odd")]}
        %p
          = link_to project.name, project
        %p.links
          = link_to image_tag('icons/application_edit.png'), edit_project_path(project), :title => 'Editar Projeto'
          = link_to image_tag('icons/group.png'), project_memberships_path(project), :title => 'Membros'
          = link_to image_tag('icons/bin.png'), { :controller => 'projects', :action => :destroy, :id => project } , :method => :delete, :confirm => 'Tem Certeza?', :title => 'Excluir projeto' if can? :destroy, project

  - if @managed_projects.present?
    %p.header Projetos - Gerente
    %p= link_to image_tag('icons/application_add.png'), new_project_path, :title => 'Criar projeto'
    - @managed_projects.each_with_index do |managed, index|
      .managed_project.project{:class => [index == 0 && "first", cycle("even", "odd")]}
        = link_to managed.name, managed
        %p.links
          = link_to image_tag('icons/application_edit.png'), edit_project_path(managed), :title => 'Editar projeto' if can? :edit, managed
          = link_to image_tag('icons/group.png'), project_memberships_path(managed), :title => 'Membros'
          = link_to image_tag('icons/bin.png'), { :controller => 'projects', :action => :destroy, :id => managed } , :method => :delete, :confirm => 'Tem Certeza?', :title => 'Excluir projeto' if can? :destroy, managed

app/views/projects/new.html.haml
.whitebox.span16
  %h1
    Novo Projeto
  = render 'form'

app/views/projects/show.html.haml
.whitebox.span16
  %h1
    = @project.name
  = "<span class='label success'>Entregue!</span>".html_safe if @project.finished?
  .row
    .span12
      %h2
        Informações:
    .span4
      %p.links
        = link_to image_tag('icons/application_edit.png').html_safe + " Editar" , edit_project_path(@project), :title => 'Editar projeto', :class => 'btn' if can? :edit, @project
        = link_to image_tag('icons/application_go.png').html_safe + " Entregar", finish_project_path(@project), :title => 'Entregar projeto', :class => 'btn success' if can?(:finish, @project) && !@project.finished?
  %h3
    Descriçao:
  %p.desc
    = @project.description
  %h3
    Data Final:
  .row
    %p.span12
      = @project.end_date
    %span.span4
      = add_to_calendar @project, :class => 'btn primary', :label => ' Adicionar ao Calendario'
  %h3
    Repositorio:
  %p.desc
    = @project.repo_url
    = link_to image_tag('icons/page_white_go.png'), tree_project_path(@project.id)
  .row
    .span12
      %h2
        Colaboradores:
    .span4
      = link_to image_tag('icons/user_add.png').html_safe + " Adicionar colaborador", new_project_membership_path(@project), :class => 'btn primary' if can? :manage_users, @project
  %ul.users
    - @project.memberships.each do |membership|
      %li.user
        %p
          = link_to image_tag('icons/delete.png'), { :controller => :memberships, :action => :destroy, :id => membership, :project_id => @project }, :method => :delete, :confirm => 'Tem certeza?' if can? :destroy, membership
          = membership.user
  .row
    .span12
      %h2
        Tarefas:
    .span4
      %p.links
        = link_to image_tag('icons/clock_add.png').html_safe + " Adicionar tarefa" , new_project_task_path(@project), :class => 'btn primary' if can? :add_task, @project
  %table
    %thead
      %tr
        %th Andamento
        %th Descrição
        %th Ações
    %tbody
      - @project.tasks.each do |task|
        %tr
          %td.span3
            = "<span class='label success'>Concluída</span>".html_safe if task.completed?
            = "<span class='label warning'>Iniciada</span>".html_safe if task.started?
            = "<span class='label important'>Não iniciada</span>".html_safe unless task.completed? || task.started?
          %td
            = link_to task, project_task_path(@project, task)
          %td.span3
            //= add_to_calendar task
            = link_to image_tag('icons/clock_stop.png').html_safe + ' Finalizar', complete_project_task_path(task.project, task), :method => :put if task.started? && can?(:manage, task)
            = link_to image_tag('icons/clock_play.png').html_safe + ' Iniciar', start_project_task_path(task.project, task), :method => :put if can?(:manage, task) && !task.started? && !task.completed?
  .row
    .span12
      %h2
        Documentos:
    .span4
      %p.links
      = link_to image_tag('icons/page_white_add.png').html_safe + ' Adicionar Documento', new_project_document_path(@project), :class => 'btn primary' if can? :add_document, @project
  %table
    %thead
      %tr
        %th Nome
        %th Ações
    %tbody
      - @project.documents.each do |doc|
        %tr
          %td
            = image_tag "icons/page_white_get.png"
            = link_to doc.file_identifier, project_document_path(doc.project,doc)
            %small
              %em= doc.description
          %td.span3
            = link_to image_tag('icons/page_white_edit.png'), edit_project_document_path(@project,doc) if can? :edit, doc
            = link_to image_tag('icons/page_white_delete.png'), {:controller => :documents, :action => :destroy, :id => doc.id, :project_id => doc.project}, :method => :delete, :confirm => 'Tem certeza?' if can? :destroy, doc

app/views/projects/tree.html.haml
.whitebox.span16
  %h1
    Repositório para
    = @project.name
  %h2
    = "#{breadcrumb(@project, @commit, params[:path])}".html_safe
  %table.zebra-striped
    %tbody
      - @tree.trees.each do |tree|
        %tr
          %td
            - path = params[:path] ? File.join(params[:path], tree.name) : tree.name
            = link_to image_tag('icons/folder.png'), tree_file_project_path(@project, :path => path, :commit_id => @commit )
            = link_to tree.name, tree_file_project_path(@project, :path => path, :commit_id => @commit )

      - @tree.blobs.each do |blob|
        %tr
          %td
            - path = params[:path] ? File.join(params[:path], blob.name) : blob.name
            =link_to image_tag('icons/page.png'), tree_file_project_path(@project, :path => path, :commit_id => @commit )
            = link_to blob.name, tree_file_project_path(@project, :path => path, :commit_id => @commit )

app/views/projects/users.html.haml
%h1 Membros
%br
- @members.each do |member|
  %p= member.to_s
%h1 Gerentes
%br
- @managers.each do |manager|
  %p= manager.to_s